# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2020 Availink, Inc. (gpl@availink.com)

ccflags-$(CONFIG_DVB_AVL_DEBUG) += -DDEBUG -g
ccflags-y += -D'pr_fmt(fmt)=KBUILD_MODNAME ": " fmt'
ccflags-$(if $(AVL_VERSION),y,) += -D'AVL_VERSION="$(AVL_VERSION)"'

ccflags-y += -I$(KERNELDIR)/drivers/media/dvb-core
ccflags-y += -I$(KERNELDIR)/drivers/media/usb/dvb-usb
ccflags-y += -I$(KERNELDIR)/drivers/media/dvb-frontends
ccflags-y += -I$(KERNELDIR)/drivers/media/tuners 
ccflags-y += -I$(PWD)/common
ccflags-y += -I$(PWD)/avl62x1/sdk_src
ccflags-y += -I$(PWD)/avl68x2/sdk_src

avl_bsp-objs := common/avl_bsp_linux.o common/avl_lib.o
avl62x1-objs := avl62x1/avl62x1_top.o avl62x1/avl62x1_api.o avl62x1/avl62x1_lib.o
avl68x2-objs := avl68x2/avl68x2_top.o avl68x2/AVL_Demod_DVBSx.o avl68x2/AVL_Demod_DVBTx.o avl68x2/AVL_Demod_CommonInternal.o avl68x2/AVL_Demod.o avl68x2/AVL_Demod_ISDBT.o avl68x2/AVL_Demod_DVBC.o

obj-$(CONFIG_DVB_AVLBSP) += avl_bsp.o
obj-$(CONFIG_DVB_AVL62X1) += avl62x1.o
obj-$(CONFIG_DVB_AVL68X2) += avl68x2.o
obj-$(if $(KBUILD_EXTMOD),m,$(CONFIG_DVB_AVL)) := avl_bsp.o avl62x1.o avl68x2.o
